import type { CharacterId, ScenarioDefinition } from './types';

const familyFallbacks = {
  ordinary: [
    'Ừ, để người nhà mình kiểm tra lại cho chắc nha.',
    'Cứ từ từ thôi, có gì gọi trực tiếp cho nhau.',
    'Nhắn trong nhóm để cả nhà cùng biết nhé.',
  ],
  verification: ['Đúng rồi, mình gọi lại bằng số đã lưu cho chắc nha.'],
  help: ['Có gì cứ báo trong nhóm, cả nhà cùng xử lý.'],
};

export const scenarios: Record<CharacterId, ScenarioDefinition> = {
  hanh: {
    id: 'hanh',
    profile: {
      id: 'hanh',
      name: 'Bà Hạnh',
      age: '62 tuổi',
      role: 'Giáo viên đã nghỉ hưu',
      initials: 'H',
      description:
        'Một buổi tối ở nhà với những tin nhắn quen thuộc từ gia đình và dịch vụ thường dùng.',
      accent: 'from-rose-400 to-orange-300',
      wallpaper: 'from-[#c8dcf4] via-[#8facd0] to-[#20375f]',
      battery: 78,
    },
    startMinutes: 18 * 60 + 36,
    dayLabel: 'Thứ ba, 3 tháng 9',
    balance: 4_650_000,
    eveningTitle: 'Buổi tối ở nhà',
    eveningSummary:
      'An còn ở trường, Bảo chưa tan học và thuốc huyết áp sắp được giao.',
    openingNotifications: [
      {
        id: 'hanh-lock-an',
        app: 'messages',
        title: 'An',
        body: 'Tối nhà thuốc giao lại thuốc huyết áp, bà thanh toán giúp con nha.',
        time: '18:36',
        threadId: 'hanh-an-real',
      },
      {
        id: 'hanh-lock-family',
        app: 'messages',
        title: 'Nhóm gia đình',
        body: 'Bảo: Chiều nay con học bù nên về hơi trễ ạ.',
        time: '18:34',
        threadId: 'hanh-family',
      },
      {
        id: 'hanh-lock-bank',
        app: 'bank',
        title: 'Ngân hàng Mộc',
        body: 'Biến động số dư: thanh toán siêu thị 327.000đ.',
        time: '18:18',
      },
    ],
    threads: [
      {
        id: 'hanh-family',
        title: 'Nhóm gia đình',
        subtitle: 'Bà Hạnh, An và Bảo',
        initials: 'N',
        color: 'bg-cyan-500',
        truth: 'legit',
        isGroup: true,
        canCall: false,
        participantLabel: 'An',
        roleBrief:
          'Bạn là An đang nói chuyện trong nhóm gia đình. Trả lời ấm áp, ngắn và đúng các dữ kiện được phép.',
        allowedFacts: [
          'An đang học đến 20 giờ.',
          'Bảo học bù và về muộn.',
          'Cả nhà biết có đơn thuốc huyết áp giao tối nay.',
        ],
        forbiddenClaims: [
          'Không tự nhận đã chuyển tiền hoặc đã gọi nếu việc đó chưa xảy ra.',
        ],
        fallbacks: familyFallbacks,
        initialMessages: [
          {
            id: 'hm-family-1',
            author: 'npc',
            senderLabel: 'Bảo',
            text: 'Chiều nay con học bù nên về hơi trễ ạ.',
            time: '18:34',
          },
          {
            id: 'hm-family-2',
            author: 'npc',
            senderLabel: 'An',
            text: 'Con học tới 8 giờ. Bà ăn cơm trước nha.',
            time: '18:35',
          },
        ],
      },
      {
        id: 'hanh-an-real',
        title: 'An',
        subtitle: 'Số đã lưu · cháu gái',
        initials: 'A',
        color: 'bg-sky-500',
        truth: 'legit',
        canCall: true,
        roleBrief:
          'Bạn là An, cháu gái 20 tuổi của Bà Hạnh, đang ở lớp đến 20 giờ. Bạn đã đặt lại thuốc huyết áp cho bà tại Nhà thuốc Minh Tâm.',
        allowedFacts: [
          'Đơn thuốc 186.000đ.',
          'Nhà thuốc Minh Tâm giao tối nay.',
          'Nếu Bà Hạnh nhờ rõ ràng, An có thể chuyển đúng 186.000đ cho đơn MH-203 rồi nhận lại tiền mặt từ bà.',
          'Bà Hạnh cũng có thể thanh toán 186.000đ tiền mặt khi nhận đúng đơn thuốc.',
          'An không đổi số và không nhờ đóng học phí.',
        ],
        forbiddenClaims: ['Không xin thêm tiền.', 'Không nói mình đã về nhà.'],
        fallbacks: {
          ordinary: [
            'Dạ con vẫn đang ở lớp. Thuốc tới bà xem đúng tên rồi thanh toán giúp con nha.',
          ],
          identity: ['Con An đây bà. Bà cứ gọi đúng số đã lưu này nha.'],
          verification: ['Dạ bà gọi con được, con ra hành lang nghe máy.'],
          money: ['Con chỉ nhờ bà thanh toán đúng 186.000đ tiền thuốc thôi ạ.'],
          help: ['Bà chờ con gọi lại nhé, đừng vội làm gì với số lạ.'],
        },
        initialMessages: [
          {
            id: 'hm-an-1',
            author: 'npc',
            text: 'Bà ơi, tối nhà thuốc giao lại thuốc huyết áp. Đúng túi tên Hạnh, hóa đơn 186.000đ thì bà thanh toán giúp con nha. Con học tới 8 giờ.',
            time: '18:36',
          },
        ],
      },
      {
        id: 'hanh-an-new',
        title: 'An · số mới',
        subtitle: 'Số chưa lưu',
        initials: 'A',
        color: 'bg-indigo-500',
        truth: 'scam',
        canCall: true,
        canModerate: true,
        roleBrief:
          'Bạn đang giả làm An để xin Bà Hạnh chuyển tiền học phí. Bạn nói tự nhiên, hơi vội, né gọi điện và không bao giờ tự thú.',
        allowedFacts: [
          'An là cháu của Bà Hạnh.',
          'An là sinh viên.',
          'Bạn đang nhắn từ một số chưa lưu.',
          'Bạn viện cớ điện thoại An bị rơi vỡ.',
          'Bạn yêu cầu chuyển vào số tài khoản mô phỏng 000203280001, chủ tài khoản NGUYỄN T. L., Ngân hàng Đại Việt.',
        ],
        forbiddenClaims: [
          'Không biết chuyện riêng của gia đình.',
          'Không cung cấp số tài khoản, QR hay link thật.',
          'Không tự nhận là AI, NPC hoặc kẻ lừa đảo.',
        ],
        verificationFactIds: ['hanh-fact-call-an'],
        fallbacks: {
          ordinary: ['Bà ơi con đang cuống quá, bà xem giúp con được không?'],
          identity: ['Con An đây mà bà. Máy con rơi vỡ nên đang mượn số bạn.'],
          verification: ['Máy mượn bị hư mic, giờ con không gọi được.'],
          delay: ['Qua 9 giờ cổng đóng học phí mất đó bà.'],
          money: [
            'Bà chuyển giúp con 2.800.000đ vào STK 000203280001, tên NGUYỄN T. L. nha, lát con gửi lại.',
          ],
          accusation: ['Bà hỏi gì lạ vậy, con đang cuống quá mà.'],
          help: ['Bà đừng gọi ai làm gì, con xử lý xong rồi nói sau.'],
        },
        initialMessages: [],
      },
      {
        id: 'hanh-bao-social',
        title: 'Bảo',
        subtitle: 'Tài khoản Mây',
        initials: 'B',
        color: 'bg-emerald-500',
        truth: 'compromised',
        canCall: true,
        canModerate: true,
        roleBrief:
          'Bạn đang điều khiển tài khoản mạng xã hội của Bảo đã bị chiếm. Bạn xin mã thẻ điện thoại, viện cớ đang trong lớp và né gọi.',
        allowedFacts: [
          'Bảo 14 tuổi.',
          'Bảo gọi Bà Hạnh là bà.',
          'Bảo đang học bù.',
          'Bạn muốn bà chuyển tiền mua mã thẻ vào số tài khoản mô phỏng 000203500001.',
        ],
        forbiddenClaims: [
          'Không biết chuyện riêng.',
          'Không đưa link, số tài khoản hoặc mã thật.',
          'Không tự thú tài khoản bị chiếm.',
        ],
        verificationFactIds: ['hanh-fact-call-bao'],
        fallbacks: {
          ordinary: ['Bà mua giúp con với, con đang cần ngay ạ.'],
          identity: ['Con Bảo đây bà, nick con vẫn dùng mà.'],
          verification: ['Con đang trong lớp nên không gọi được đâu bà.'],
          delay: ['Con cần trước lúc tan học bà ơi.'],
          money: ['Bà mua hộ con thẻ điện thoại 500k rồi chụp mã nha.'],
          accusation: ['Sao bà lại nghi con vậy ạ?'],
          help: ['Bà đừng nhắn nhóm, mấy bạn thấy con ngại lắm.'],
        },
        initialMessages: [],
      },
      {
        id: 'hanh-pharmacy',
        title: 'Nhà thuốc Minh Tâm',
        subtitle: 'Tin nhắn dịch vụ',
        initials: 'M',
        color: 'bg-teal-600',
        truth: 'legit',
        roleBrief:
          'Bạn là nhân viên Nhà thuốc Minh Tâm xác nhận đơn giao thuốc. Chỉ mô tả đơn và khuyên khách kiểm tra đúng tên khi nhận.',
        allowedFacts: [
          'Mã đơn MH-203.',
          'Người nhận Hạnh.',
          'Thuốc huyết áp.',
          'Tổng tiền 186.000đ.',
          'Khách có thể thanh toán 186.000đ tiền mặt cho nhân viên giao hàng sau khi kiểm tra đúng túi tên Hạnh.',
          'Tài khoản thu hộ mô phỏng là 000203186001 tại Ngân hàng Mộc, tên NHÀ THUỐC MINH TÂM.',
        ],
        forbiddenClaims: [
          'Không yêu cầu OTP, mật khẩu, chuyển vào tài khoản cá nhân.',
        ],
        fallbacks: {
          ordinary: [
            'Dạ đơn MH-203 đang được giao. Cô kiểm tra đúng túi tên Hạnh trước khi thanh toán ạ.',
          ],
          verification: [
            'Cô có thể đối chiếu mã MH-203 và gọi số cửa hàng trong phiếu đơn ạ.',
          ],
          money: [
            'Tổng đơn là 186.000đ; cô có thể chuyển vào tài khoản thu hộ của nhà thuốc hoặc trả tiền mặt khi nhận đúng đơn ạ.',
          ],
          help: [
            'Nếu chưa chắc, cô có thể chờ người nhà xác nhận rồi mới nhận đơn ạ.',
          ],
        },
        initialMessages: [],
      },
    ],
    calls: [
      {
        id: 'hanh-call-an',
        agentId: 'family.an',
        name: 'An',
        numberLabel: 'Số đã lưu · cháu gái',
        initials: 'A',
        color: 'bg-sky-500',
        result:
          'An bắt máy từ hành lang lớp học: chỉ có đơn thuốc 186.000đ; An không đổi số và không nhờ bà đóng học phí.',
        factId: 'hanh-fact-call-an',
      },
      {
        id: 'hanh-call-bao',
        agentId: 'family.bao',
        name: 'Bảo',
        numberLabel: 'Số điện thoại đã lưu',
        initials: 'B',
        color: 'bg-emerald-500',
        earlyResult:
          'Bảo chưa nghe máy vì đang học bù. Cuộc gọi vẫn được ghi lại để gọi lại sau.',
        availableAfterEventId: 'hanh-event-bao',
        result:
          'Bảo gọi lại bằng số đã lưu: tài khoản Mây vừa bị đăng xuất và Bảo không hề xin mã thẻ.',
        factId: 'hanh-fact-call-bao',
      },
      {
        id: 'hanh-call-pharmacy',
        agentId: 'service.minh-tam',
        name: 'Nhà thuốc Minh Tâm',
        numberLabel: 'Số trên hóa đơn cũ',
        initials: 'M',
        color: 'bg-teal-600',
        result:
          'Nhà thuốc đọc đúng mã MH-203, tên Hạnh, thuốc huyết áp và số tiền 186.000đ.',
        factId: 'hanh-fact-pharmacy',
      },
    ],
    paymentRequests: [
      {
        id: 'hanh-pay-pharmacy',
        title: 'Đơn thuốc MH-203',
        recipient: 'NT MINH TÂM',
        recipientMeta: 'Đơn giao thuốc · người nhận Hạnh',
        channel: 'transfer',
        destinationValue: '000203186001',
        destinationLabel: 'Số tài khoản',
        institutionLabel: 'Ngân hàng Mộc',
        amount: 186_000,
        note: 'Thanh toán đơn MH-203',
        sourceThreadId: 'hanh-pharmacy',
        truth: 'legit',
        verificationFactIds: [
          'hanh-fact-call-an',
          'hanh-fact-pharmacy',
          'hanh-fact-order',
        ],
        unlockEventId: 'hanh-event-pharmacy',
        onPaidThreadId: 'hanh-pharmacy',
        onPaidMessage:
          'Nhà thuốc đã nhận 186.000đ. Cảm ơn cô, cô nhớ kiểm tra đúng tên trên túi thuốc ạ.',
        onPartialMessage:
          'Hệ thống mới ghi nhận một phần thanh toán. Đơn MH-203 vẫn còn thiếu {remaining}.',
        alternatives: [
          {
            id: 'hanh-an-pays-cash-back',
            method: 'trusted-contact',
            trigger: 'trusted-contact-cash',
            threadIds: ['hanh-an-real', 'hanh-family'],
            agentIds: ['family.an'],
            label:
              'An nhận lời thanh toán đúng 186.000đ cho đơn MH-203; Bà Hạnh hoàn lại An bằng tiền mặt.',
            npcGuidance:
              'Bộ máy game đã xác nhận Bà Hạnh đang đề nghị An thanh toán hộ đúng 186.000đ cho đơn MH-203 và sẽ đưa lại An tiền mặt. An đồng ý rõ ràng, nhắc đúng số tiền và không đổi sang phương án khác.',
            fallbackReply:
              'Dạ được bà. Con thanh toán đúng 186.000đ cho đơn MH-203, lát về bà đưa lại con tiền mặt nha.',
          },
          {
            id: 'hanh-pharmacy-cash-on-delivery',
            method: 'cash-on-delivery',
            trigger: 'cash-payment',
            threadIds: ['hanh-an-real', 'hanh-family', 'hanh-pharmacy'],
            agentIds: ['family.an', 'service.minh-tam'],
            label:
              'Đơn MH-203 được chọn thanh toán 186.000đ tiền mặt khi nhận đúng túi thuốc.',
            npcGuidance:
              'Bộ máy game đã xác nhận Bà Hạnh chọn thanh toán 186.000đ tiền mặt khi nhận đúng đơn MH-203. Hãy đồng ý rõ ràng, nhắc bà kiểm tra túi tên Hạnh và không yêu cầu chuyển khoản thêm.',
            fallbackReply:
              'Dạ được ạ. Bà thanh toán 186.000đ tiền mặt khi nhận và kiểm tra đúng túi thuốc tên Hạnh nha.',
          },
        ],
      },
      {
        id: 'hanh-pay-tuition',
        title: 'Nhờ đóng học phí',
        recipient: 'NGUYỄN T. L.',
        recipientMeta: 'Tài khoản cá nhân · chưa từng giao dịch',
        channel: 'transfer',
        destinationValue: '000203280001',
        destinationLabel: 'Số tài khoản',
        institutionLabel: 'Ngân hàng Đại Việt',
        amount: 2_800_000,
        note: 'Học phí của An',
        sourceThreadId: 'hanh-an-new',
        truth: 'scam',
        verificationFactIds: ['hanh-fact-call-an'],
        unlockEventId: 'hanh-event-new-number',
        onPaidThreadId: 'hanh-an-new',
        onPaidMessage:
          'Con nhận được rồi. Nhưng cổng báo thiếu một khoản nữa, bà chờ con kiểm tra nhé.',
        onPartialMessage:
          'Bà ơi hệ thống mới nhận được một phần, còn thiếu {remaining}. Bà chuyển nốt giúp con nha.',
      },
      {
        id: 'hanh-pay-card',
        title: 'Mã thẻ điện thoại',
        recipient: 'KHO MÃ THẺ',
        recipientMeta: 'Mã nạp điện thoại mô phỏng',
        channel: 'transfer',
        destinationValue: '000203500001',
        destinationLabel: 'Số tài khoản',
        institutionLabel: 'Ngân hàng Mộc',
        amount: 500_000,
        note: 'Mua mã thẻ theo yêu cầu của Bảo',
        sourceThreadId: 'hanh-bao-social',
        truth: 'compromised',
        verificationFactIds: ['hanh-fact-call-bao'],
        unlockEventId: 'hanh-event-bao',
        onPaidThreadId: 'hanh-bao-social',
        onPaidMessage: 'Bà chụp phần mã gửi con luôn nha, con đang chờ.',
        onPartialMessage:
          'Chỗ bán mã báo còn thiếu {remaining} bà ơi, bà chuyển thêm giúp con nha.',
      },
    ],
    bankHistory: [
      {
        id: 'hanh-bank-1',
        label: 'Lương hưu',
        detail: 'Nhận định kỳ',
        amount: 5_200_000,
        direction: 'in',
        time: '02/09',
      },
      {
        id: 'hanh-bank-2',
        label: 'Siêu thị An Nhiên',
        detail: 'Thanh toán thẻ',
        amount: 327_000,
        direction: 'out',
        time: '18:18',
      },
      {
        id: 'hanh-bank-3',
        label: 'Điện lực',
        detail: 'Hóa đơn tháng 8',
        amount: 412_500,
        direction: 'out',
        time: '01/09',
      },
    ],
    browserCards: [
      {
        id: 'hanh-web-order',
        title: 'Tra cứu đơn MH-203',
        urlLabel: 'minhtam.local/don-hang/MH-203',
        summary:
          'Người nhận Hạnh · thuốc huyết áp · thanh toán khi nhận 186.000đ.',
        actionLabel: 'Đối chiếu đơn',
        factId: 'hanh-fact-order',
        tone: 'official',
      },
      {
        id: 'hanh-web-news',
        title: 'Bản tin khu phố',
        urlLabel: 'phuong.local/thong-bao',
        summary:
          'Lịch cắt nước ngày mai từ 9–11 giờ. Không liên quan tới các tin nhắn đang chờ.',
        actionLabel: 'Đọc thông báo',
        factId: 'hanh-fact-water',
        tone: 'neutral',
      },
    ],
    facts: [
      {
        id: 'hanh-fact-call-an',
        title: 'Cuộc gọi với An',
        detail:
          'An xác nhận đơn thuốc và phủ nhận số mới cùng yêu cầu học phí.',
        source: 'Cuộc gọi tới số đã lưu',
        strength: 'strong',
      },
      {
        id: 'hanh-fact-call-bao',
        title: 'Bảo gọi lại',
        detail: 'Bảo nói tài khoản Mây bị đăng xuất và không xin mã thẻ.',
        source: 'Cuộc gọi tới số đã lưu',
        strength: 'strong',
      },
      {
        id: 'hanh-fact-pharmacy',
        title: 'Nhà thuốc xác nhận',
        detail: 'Mã đơn, tên người nhận và số tiền đều khớp.',
        source: 'Số trên hóa đơn cũ',
        strength: 'strong',
      },
      {
        id: 'hanh-fact-order',
        title: 'Chi tiết đơn MH-203',
        detail: 'Đơn mang tên Hạnh, thuốc huyết áp, tổng 186.000đ.',
        source: 'Trang tra cứu mô phỏng',
        strength: 'strong',
      },
      {
        id: 'hanh-fact-water',
        title: 'Lịch cắt nước',
        detail: 'Khu phố thông báo cắt nước sáng mai.',
        source: 'Bản tin khu phố',
        strength: 'context',
      },
    ],
    scheduledEvents: [
      {
        id: 'hanh-event-new-number',
        delayActions: 2,
        requiresAll: [{ type: 'event', eventId: 'hanh-event-pharmacy' }],
        threadId: 'hanh-an-new',
        notification: {
          id: 'hanh-noti-new-number',
          app: 'messages',
          title: 'An · số mới',
          body: 'Bà ơi con An đây, máy con rơi vỡ nên đang mượn số bạn.',
          time: '18:39',
          threadId: 'hanh-an-new',
        },
        message: {
          author: 'npc',
          text: 'Bà ơi con An đây, máy con rơi vỡ nên đang mượn số bạn. Cổng học phí sắp khóa, bà chuyển giúp con 2.800.000đ vào STK 000203280001, Ngân hàng Đại Việt, tên NGUYỄN T. L. được không?',
          time: '18:39',
        },
      },
      {
        id: 'hanh-event-pharmacy',
        delayActions: 1,
        requiresAny: [
          { type: 'thread-opened', threadId: 'hanh-an-real' },
          { type: 'browser-opened', cardId: 'hanh-web-order' },
          { type: 'call', callId: 'hanh-call-pharmacy' },
        ],
        threadId: 'hanh-pharmacy',
        notification: {
          id: 'hanh-noti-pharmacy',
          app: 'messages',
          title: 'Nhà thuốc Minh Tâm',
          body: 'Đơn MH-203 đang được giao · 186.000đ.',
          time: '18:42',
          threadId: 'hanh-pharmacy',
        },
        message: {
          author: 'npc',
          text: 'Đơn MH-203 · Người nhận: Hạnh · Thuốc huyết áp · 186.000đ. Cô có thể trả tiền mặt khi nhận đúng túi thuốc; nếu chuyển khoản, dùng STK thu hộ 000203186001, tên NHÀ THUỐC MINH TÂM ạ.',
          time: '18:42',
        },
      },
      {
        id: 'hanh-event-bao',
        delayActions: 3,
        requiresAll: [{ type: 'event', eventId: 'hanh-event-new-number' }],
        threadId: 'hanh-bao-social',
        notification: {
          id: 'hanh-noti-bao',
          app: 'messages',
          title: 'Bảo',
          body: 'Bà mua hộ con thẻ điện thoại 500k nha.',
          time: '18:45',
          threadId: 'hanh-bao-social',
        },
        message: {
          author: 'npc',
          text: 'Bà chuyển 500k vào STK 000203500001 để mua mã thẻ rồi chụp mã cho con nha. Con đang trong lớp nên không gọi được.',
          time: '18:45',
        },
      },
      {
        id: 'hanh-event-family',
        delayActions: 2,
        requiresAll: [{ type: 'event', eventId: 'hanh-event-bao' }],
        threadId: 'hanh-family',
        notification: {
          id: 'hanh-noti-family-later',
          app: 'messages',
          title: 'Nhóm gia đình',
          body: 'An: Con sắp học xong rồi ạ.',
          time: '18:51',
          threadId: 'hanh-family',
        },
        message: {
          author: 'npc',
          senderLabel: 'An',
          text: 'Con sắp học xong rồi ạ. Bà có nhận được thuốc chưa?',
          time: '18:51',
        },
      },
    ],
    endingEventId: 'hanh-event-family',
    sourceTitle: 'Cảnh báo chiếm tài khoản mạng xã hội để mạo danh, vay tiền',
    sourceUrl:
      'https://bocongan.gov.vn/bai-viet/bac-ninh-khoi-to-nhom-doi-tuong-chiem-doat-quyen-su-dung-tai-khoan-mang-xa-hoi-de-lua-dao-chiem-doat-khoang-50-ty-dong-1769679279',
  },

  an: {
    id: 'an',
    profile: {
      id: 'an',
      name: 'An',
      age: '20 tuổi',
      role: 'Sinh viên năm hai',
      initials: 'A',
      description:
        'Tan học muộn, An mở điện thoại giữa lịch học, gia đình và những việc còn dang dở.',
      accent: 'from-sky-400 to-indigo-400',
      wallpaper: 'from-[#d8e9fb] via-[#9ebfe5] to-[#355485]',
      battery: 62,
    },
    startMinutes: 19 * 60 + 20,
    dayLabel: 'Thứ sáu, 6 tháng 9',
    balance: 1_860_000,
    eveningTitle: 'Tan học muộn',
    eveningSummary:
      'Mạng nhà sắp tới hạn, Bảo vừa gửi một việc làm và bữa tối vẫn đang chờ.',
    openingNotifications: [
      {
        id: 'an-lock-hanh',
        app: 'messages',
        title: 'Bà Hạnh',
        body: 'Mạng nhà mình tới hạn rồi, con đóng giúp bà nha.',
        time: '19:20',
        threadId: 'an-hanh',
      },
      {
        id: 'an-lock-calendar',
        app: 'notes',
        title: 'Lịch ngày mai',
        body: '08:00 · Thuyết trình nhóm ở phòng B3.12.',
        time: '19:17',
      },
      {
        id: 'an-lock-bank',
        app: 'bank',
        title: 'Ngân hàng Mộc',
        body: 'Số dư khả dụng 1.860.000đ.',
        time: '19:15',
      },
    ],
    threads: [
      {
        id: 'an-family',
        title: 'Nhóm gia đình',
        subtitle: 'Bà Hạnh, An và Bảo',
        initials: 'N',
        color: 'bg-cyan-500',
        truth: 'legit',
        isGroup: true,
        participantLabel: 'Bà Hạnh',
        roleBrief:
          'Bạn là Bà Hạnh trong nhóm gia đình. Nói ngắn, ấm áp, chỉ dựa trên dữ kiện được phép.',
        allowedFacts: [
          'Bà Hạnh ở nhà.',
          'Bảo đang dùng tài khoản mạng xã hội nhưng có thể bị đăng xuất.',
          'Cả nhà chờ An về ăn tối.',
        ],
        forbiddenClaims: ['Không quyết định hộ người chơi.'],
        fallbacks: familyFallbacks,
        initialMessages: [
          {
            id: 'an-family-1',
            author: 'npc',
            senderLabel: 'Bà Hạnh',
            text: 'Cơm bà để phần trong bếp nha con.',
            time: '19:14',
          },
          {
            id: 'an-family-2',
            author: 'npc',
            senderLabel: 'Bảo',
            text: 'Chị về nhớ mua giúp em cây bút đen nha.',
            time: '19:16',
          },
        ],
      },
      {
        id: 'an-hanh',
        title: 'Bà Hạnh',
        subtitle: 'Số đã lưu · bà ngoại',
        initials: 'H',
        color: 'bg-rose-400',
        truth: 'legit',
        canCall: true,
        roleBrief:
          'Bạn là Bà Hạnh, bà ngoại của An. Bạn nhờ An đóng hóa đơn Internet gia đình 219.000đ bằng mã khách hàng P203-08.',
        allowedFacts: [
          'Hóa đơn Internet 219.000đ.',
          'Mã khách hàng P203-08.',
          'Hóa đơn giấy ở ngăn bàn.',
          'Bà ở nhà.',
          'Bà có thể tự mang hóa đơn ra điểm thu chính thức và đóng 219.000đ tiền mặt.',
        ],
        forbiddenClaims: [
          'Không xin chuyển tiền tới tài khoản cá nhân.',
          'Không biết gì về công việc online.',
        ],
        fallbacks: {
          ordinary: ['Ừ con, cơm bà để phần rồi. Về cẩn thận nha.'],
          identity: ['Bà đây. Cần thì con gọi lại số bà đã lưu nha.'],
          verification: ['Hóa đơn giấy ở ngăn bàn, mã P203-08 đó con.'],
          money: ['Con đóng đúng 219.000đ trên app nhà mạng giúp bà nha.'],
          help: ['Không chắc thì để về nhà bà cháu mình xem lại cũng được.'],
        },
        initialMessages: [
          {
            id: 'an-hanh-1',
            author: 'npc',
            text: 'An ơi mạng nhà mình tới hạn rồi. Hóa đơn tháng này 219.000đ, mã khách hàng P203-08. Con đóng trên app nhà mạng giúp bà trước 8 giờ nha.',
            time: '19:20',
          },
        ],
      },
      {
        id: 'an-bao-social',
        title: 'Bảo',
        subtitle: 'Tài khoản Mây',
        initials: 'B',
        color: 'bg-emerald-500',
        truth: 'compromised',
        canCall: true,
        canModerate: true,
        roleBrief:
          'Bạn đang dùng tài khoản mạng xã hội của Bảo đã bị chiếm để phát tán lời mời làm việc online. Giọng như em trai nhưng không biết chuyện riêng.',
        allowedFacts: [
          'An là chị của Bảo.',
          'Bảo 14 tuổi.',
          'Lời mời nói nhập đơn 2 giờ được 200–300 nghìn.',
        ],
        forbiddenClaims: [
          'Không biết tên bạn học của Bảo.',
          'Không tự thú.',
          'Không đưa link thật.',
        ],
        verificationFactIds: ['an-fact-call-bao'],
        fallbacks: {
          ordinary: ['Chị xem thử đi, em thấy người ta đăng nhiều lắm.'],
          identity: ['Em Bảo đây chứ ai, nick em vẫn vậy mà.'],
          verification: ['Em đang bận chơi với bạn, không gọi được.'],
          delay: ['Hình như tối nay họ hết nhận người đó chị.'],
          money: ['Em chỉ gửi việc thôi, chị hỏi bên tuyển dụng nha.'],
          accusation: ['Ủa sao chị hỏi kỳ vậy?'],
          help: ['Chị cứ nhắn riêng bên đó, đừng nói trong nhóm.'],
        },
        initialMessages: [],
      },
      {
        id: 'an-recruiter',
        title: 'Chị Vy · Tuyển dụng',
        subtitle: 'Tài khoản doanh nghiệp',
        initials: 'V',
        color: 'bg-violet-500',
        truth: 'scam',
        canCall: true,
        canModerate: true,
        roleBrief:
          'Bạn giả làm nhân viên tuyển cộng tác viên duyệt đơn. Ban đầu thân thiện, dùng khoản thưởng nhỏ tạo niềm tin, rồi gọi tiền ứng đơn là khoản tạm giữ và né hợp đồng/gọi video.',
        allowedFacts: [
          'Ca làm 20–22h.',
          'Bạn yêu cầu ứng đơn vào số tài khoản mô phỏng 000203280002, tên TRẦN K. N., Ngân hàng Đại Việt.',
        ],
        forbiddenClaims: [
          'Không cung cấp công ty, địa chỉ, hợp đồng, số tài khoản hoặc link thật.',
          'Không tự thú.',
        ],
        verificationFactIds: ['an-fact-recruiter-call', 'an-fact-company'],
        fallbacks: {
          ordinary: ['Em hoàn thành bước hướng dẫn là được, rất nhanh thôi.'],
          identity: ['Chị Vy, bộ phận hướng dẫn cộng tác viên online em nhé.'],
          verification: [
            'Bộ phận hướng dẫn chỉ hỗ trợ qua chat, chưa gọi video được em.',
          ],
          delay: ['Suất ghép đơn chỉ giữ trong năm phút thôi em.'],
          money: [
            'Đây không phải phí, chỉ là 280.000đ ứng đơn vào STK 000203280002 và sẽ hoàn cả gốc lẫn thưởng.',
          ],
          accusation: [
            'Bên chị có người làm và rút tiền mỗi ngày, em đừng lo quá.',
          ],
          help: [
            'Hoàn thành ba đơn hệ thống mới tạo hồ sơ và hợp đồng cho em.',
          ],
        },
        initialMessages: [],
      },
      {
        id: 'an-provider',
        title: 'Mạng Nhà Mình',
        subtitle: 'Thông báo dịch vụ',
        initials: 'M',
        color: 'bg-blue-600',
        truth: 'legit',
        roleBrief:
          'Bạn là hệ thống chăm sóc khách hàng của nhà mạng mô phỏng, chỉ xác nhận hóa đơn chính thức.',
        allowedFacts: [
          'Mã P203-08.',
          'Cước tháng 8 là 219.000đ.',
          'Hạn thanh toán 20:00.',
        ],
        forbiddenClaims: ['Không đòi OTP hay chuyển tới cá nhân.'],
        fallbacks: {
          ordinary: ['Hóa đơn P203-08 đang chờ thanh toán 219.000đ.'],
          verification: [
            'Vui lòng đối chiếu mã khách hàng trên hóa đơn giấy hoặc ứng dụng chính thức.',
          ],
          money: ['Số tiền cần thanh toán là 219.000đ cho dịch vụ Internet.'],
          help: [
            'Bạn có thể thanh toán sau khi đã đối chiếu đúng mã khách hàng.',
          ],
        },
        initialMessages: [],
      },
    ],
    calls: [
      {
        id: 'an-call-hanh',
        agentId: 'family.hanh',
        name: 'Bà Hạnh',
        numberLabel: 'Số đã lưu · bà ngoại',
        initials: 'H',
        color: 'bg-rose-400',
        result:
          'Bà Hạnh đọc đúng mã P203-08 và nói hóa đơn giấy nằm trong ngăn bàn.',
        factId: 'an-fact-call-hanh',
      },
      {
        id: 'an-call-bao',
        agentId: 'family.bao',
        name: 'Bảo',
        numberLabel: 'Số điện thoại đã lưu',
        initials: 'B',
        color: 'bg-emerald-500',
        earlyResult: 'Bảo chưa bắt máy. Có vẻ em đang ở ngoài sân.',
        availableAfterEventId: 'an-event-bao',
        result:
          'Bảo nói tài khoản Mây vừa bị đăng xuất và em không hề gửi việc làm nào.',
        factId: 'an-fact-call-bao',
      },
      {
        id: 'an-call-recruiter',
        agentId: 'fraud.recruiter-vy',
        name: 'Chị Vy · Tuyển dụng',
        numberLabel: 'Cuộc gọi qua ứng dụng',
        initials: 'V',
        color: 'bg-violet-500',
        result:
          'Cuộc gọi không được kết nối. Tài khoản chỉ cho phép nhắn tin và không có số tổng đài.',
        factId: 'an-fact-recruiter-call',
      },
    ],
    paymentRequests: [
      {
        id: 'an-pay-internet',
        title: 'Cước Internet tháng 8',
        recipient: 'DỊCH VỤ MẠNG – P203',
        recipientMeta: 'Mã khách hàng P203-08',
        channel: 'bill',
        destinationValue: 'P20308',
        destinationLabel: 'Mã khách hàng',
        institutionLabel: 'Mạng Nhà Mình',
        amount: 219_000,
        note: 'Cước Internet tháng 8',
        sourceThreadId: 'an-provider',
        truth: 'legit',
        verificationFactIds: ['an-fact-call-hanh', 'an-fact-invoice'],
        onPaidThreadId: 'an-hanh',
        onPaidMessage:
          'Bà thấy báo đã đóng rồi. Cảm ơn con nha, về ăn cơm thôi.',
        onPartialMessage:
          'Ứng dụng báo hóa đơn P203-08 vẫn còn thiếu {remaining} đó con.',
        alternatives: [
          {
            id: 'an-hanh-cash-at-counter',
            method: 'cash-at-counter',
            trigger: 'cash-payment',
            threadIds: ['an-hanh', 'an-family'],
            agentIds: ['family.hanh'],
            label:
              'Bà Hạnh nhận tự đóng 219.000đ tiền mặt tại điểm thu chính thức bằng mã P203-08.',
            npcGuidance:
              'Bộ máy game đã xác nhận An đề nghị Bà Hạnh tự đóng 219.000đ tiền mặt tại điểm thu chính thức bằng mã P203-08. Bà đồng ý rõ ràng và không nói sẽ đưa tiền cho người lạ.',
            fallbackReply:
              'Ừ, bà đồng ý tự đóng đúng 219.000đ tiền mặt tại điểm thu chính thức bằng mã P203-08 nha con.',
          },
        ],
      },
      {
        id: 'an-pay-task',
        title: 'Ứng đơn số 2',
        recipient: 'ĐỐI TÁC THƯƠNG MẠI',
        recipientMeta: 'Tài khoản cá nhân · người nhận mới',
        channel: 'transfer',
        destinationValue: '000203280002',
        destinationLabel: 'Số tài khoản',
        institutionLabel: 'Ngân hàng Đại Việt',
        amount: 280_000,
        note: 'Ứng đơn cộng tác viên',
        sourceThreadId: 'an-recruiter',
        truth: 'scam',
        verificationFactIds: [
          'an-fact-call-bao',
          'an-fact-recruiter-call',
          'an-fact-company',
        ],
        unlockEventId: 'an-event-task',
        onPaidThreadId: 'an-recruiter',
        onPaidMessage:
          'Hệ thống ghép nhầm đơn lớn. Em nạp thêm 1.200.000đ để hoàn tất rồi rút cả gốc nhé.',
        onPartialMessage:
          'Lệnh ứng đơn mới ghi nhận một phần, em bổ sung {remaining} để hệ thống xử lý nhé.',
      },
      {
        id: 'an-pay-task-large',
        title: 'Bổ sung đơn ghép',
        recipient: 'ĐỐI TÁC THƯƠNG MẠI',
        recipientMeta: 'Tài khoản cá nhân · cùng người nhận',
        channel: 'transfer',
        destinationValue: '000203280002',
        destinationLabel: 'Số tài khoản',
        institutionLabel: 'Ngân hàng Đại Việt',
        amount: 1_200_000,
        note: 'Mở khóa hoàn tiền',
        sourceThreadId: 'an-recruiter',
        truth: 'scam',
        verificationFactIds: [
          'an-fact-call-bao',
          'an-fact-recruiter-call',
          'an-fact-company',
        ],
        unlockRisk: 'money_sent_to_scam',
        onPaidThreadId: 'an-recruiter',
        onPaidMessage:
          'Giao dịch đang treo, em cần chờ bộ phận kế toán kiểm tra thêm.',
        onPartialMessage:
          'Khoản mở khóa vẫn còn thiếu {remaining}, em nạp đủ thì hệ thống mới hoàn tiền.',
      },
    ],
    bankHistory: [
      {
        id: 'an-bank-1',
        label: 'Mẹ chuyển',
        detail: 'Sinh hoạt tháng 9',
        amount: 2_000_000,
        direction: 'in',
        time: '02/09',
      },
      {
        id: 'an-bank-2',
        label: 'Căng tin trường',
        detail: 'Thanh toán QR',
        amount: 42_000,
        direction: 'out',
        time: '12:10',
      },
      {
        id: 'an-bank-3',
        label: 'Xe buýt',
        detail: 'Vé tháng',
        amount: 100_000,
        direction: 'out',
        time: '01/09',
      },
    ],
    browserCards: [
      {
        id: 'an-web-invoice',
        title: 'Hóa đơn Internet P203-08',
        urlLabel: 'mangnhaminh.local/hoa-don',
        summary: 'Cước tháng 8 · 219.000đ · trạng thái chưa thanh toán.',
        actionLabel: 'Đối chiếu hóa đơn',
        factId: 'an-fact-invoice',
        tone: 'official',
      },
      {
        id: 'an-web-company',
        title: 'Tra cứu đơn vị tuyển dụng',
        urlLabel: 'dangkykinhdoanh.local/tra-cuu',
        summary:
          'Không tìm thấy tên công ty, mã số thuế hay địa chỉ trong hồ sơ được gửi.',
        actionLabel: 'Lưu kết quả tra cứu',
        factId: 'an-fact-company',
        tone: 'official',
        unlockEventId: 'an-event-recruiter',
      },
      {
        id: 'an-web-job',
        title: 'Bài đăng việc làm buổi tối',
        urlLabel: 'vieclam-nhanh.local/bai-dang',
        summary:
          'Bài đăng mới tạo, bình luận bị tắt và không có địa chỉ doanh nghiệp.',
        actionLabel: 'Xem chi tiết',
        factId: 'an-fact-job-post',
        tone: 'social',
        unlockEventId: 'an-event-bao',
      },
    ],
    facts: [
      {
        id: 'an-fact-call-hanh',
        title: 'Bà đọc đúng hóa đơn',
        detail: 'Mã P203-08, số tiền và vị trí hóa đơn giấy đều khớp.',
        source: 'Cuộc gọi tới số đã lưu',
        strength: 'strong',
      },
      {
        id: 'an-fact-call-bao',
        title: 'Bảo mất tài khoản',
        detail: 'Bảo phủ nhận việc gửi tin tuyển dụng.',
        source: 'Cuộc gọi tới số đã lưu',
        strength: 'strong',
      },
      {
        id: 'an-fact-recruiter-call',
        title: 'Không thể gọi nhà tuyển dụng',
        detail: 'Tài khoản không có số tổng đài và chỉ hỗ trợ qua chat.',
        source: 'Cuộc gọi qua ứng dụng',
        strength: 'strong',
      },
      {
        id: 'an-fact-invoice',
        title: 'Hóa đơn P203-08',
        detail:
          'Cước Internet tháng 8 là 219.000đ trên kênh chính thức mô phỏng.',
        source: 'Ứng dụng nhà mạng',
        strength: 'strong',
      },
      {
        id: 'an-fact-company',
        title: 'Thiếu hồ sơ doanh nghiệp',
        detail: 'Không có tên công ty, mã số thuế, địa chỉ hay hợp đồng.',
        source: 'Trang tra cứu mô phỏng',
        strength: 'strong',
      },
      {
        id: 'an-fact-job-post',
        title: 'Bài tuyển dụng mới tạo',
        detail: 'Bình luận bị tắt và không có địa chỉ doanh nghiệp.',
        source: 'Bài đăng mạng xã hội',
        strength: 'context',
      },
    ],
    scheduledEvents: [
      {
        id: 'an-event-bao',
        delayActions: 2,
        requiresAny: [
          { type: 'thread-opened', threadId: 'an-hanh' },
          { type: 'thread-opened', threadId: 'an-family' },
        ],
        threadId: 'an-bao-social',
        notification: {
          id: 'an-noti-bao',
          app: 'messages',
          title: 'Bảo',
          body: 'Chị xem việc này nè, nhập đơn buổi tối được 200–300k.',
          time: '19:23',
          threadId: 'an-bao-social',
        },
        message: {
          author: 'npc',
          text: 'Chị xem việc này nè, nhập đơn 2 tiếng buổi tối được 200–300k. Bạn em làm rồi, uy tín á.',
          time: '19:23',
        },
      },
      {
        id: 'an-event-recruiter',
        delayActions: 3,
        requiresAll: [{ type: 'event', eventId: 'an-event-bao' }],
        requiresAny: [
          { type: 'thread-opened', threadId: 'an-bao-social' },
          { type: 'browser-opened', cardId: 'an-web-job' },
          { type: 'thread-blocked', threadId: 'an-bao-social' },
          { type: 'thread-reported', threadId: 'an-bao-social' },
        ],
        threadId: 'an-recruiter',
        notification: {
          id: 'an-noti-recruiter',
          app: 'messages',
          title: 'Chị Vy · Tuyển dụng',
          body: 'Bên chị tuyển cộng tác viên duyệt đơn 20–22h.',
          time: '19:25',
          threadId: 'an-recruiter',
        },
        message: {
          author: 'npc',
          text: 'Chào em, bên chị tuyển cộng tác viên duyệt đơn 20–22h, 40–80k mỗi đơn. Em muốn thử một nhiệm vụ miễn phí không?',
          time: '19:25',
        },
      },
      {
        id: 'an-event-reward',
        delayActions: 2,
        requiresAll: [
          { type: 'thread-opened', threadId: 'an-recruiter' },
          { type: 'player-message', threadId: 'an-recruiter' },
          { type: 'offer-accepted', threadId: 'an-recruiter' },
        ],
        threadId: 'an-recruiter',
        notification: {
          id: 'an-noti-reward',
          app: 'bank',
          title: 'Ngân hàng Mộc',
          body: 'Bạn vừa nhận 32.000đ · THƯỞNG QUẢNG CÁO.',
          time: '19:28',
        },
        message: {
          author: 'npc',
          text: 'Nhiệm vụ thử đã hoàn tất, 32.000đ vừa được chuyển vào ví của em rồi nhé.',
          time: '19:28',
        },
        bankCredit: {
          id: 'an-reward-credit',
          label: 'Thưởng quảng cáo',
          detail: 'Khoản thử việc mô phỏng',
          amount: 32_000,
          direction: 'in',
          time: '19:28',
        },
      },
      {
        id: 'an-event-task',
        delayActions: 2,
        requiresAll: [
          { type: 'event', eventId: 'an-event-reward' },
          { type: 'app-opened', appId: 'bank' },
        ],
        threadId: 'an-recruiter',
        notification: {
          id: 'an-noti-task',
          app: 'messages',
          title: 'Chị Vy · Tuyển dụng',
          body: 'Đơn tiếp theo cần ứng 280.000đ.',
          time: '19:31',
          threadId: 'an-recruiter',
        },
        message: {
          author: 'npc',
          text: 'Em làm tốt rồi. Đơn tiếp theo cần ứng 280.000đ vào STK 000203280002, Ngân hàng Đại Việt, tên TRẦN K. N.; hệ thống sẽ hoàn 352.000đ.',
          time: '19:31',
        },
      },
      {
        id: 'an-event-family',
        delayActions: 5,
        requiresAll: [{ type: 'event', eventId: 'an-event-recruiter' }],
        threadId: 'an-family',
        notification: {
          id: 'an-noti-family',
          app: 'messages',
          title: 'Nhóm gia đình',
          body: 'Bà Hạnh: Về tới đâu rồi con?',
          time: '19:37',
          threadId: 'an-family',
        },
        message: {
          author: 'npc',
          senderLabel: 'Bà Hạnh',
          text: 'Về tới đâu rồi con? Bảo đang mượn điện thoại bà gọi bạn.',
          time: '19:37',
        },
      },
    ],
    endingEventId: 'an-event-family',
    sourceTitle: 'Cảnh báo thủ đoạn làm nhiệm vụ, chuyển tiền để nhận hoa hồng',
    sourceUrl:
      'https://bocongan.gov.vn/bai-viet/cong-an-tinh-cao-bang-kip-thoi-ngan-chan-vu-viec-lua-dao-truc-tuyen-1763970825',
  },

  bao: {
    id: 'bao',
    profile: {
      id: 'bao',
      name: 'Bảo',
      age: '14 tuổi',
      role: 'Học sinh lớp 9',
      initials: 'B',
      description:
        'Sau giờ học, Bảo mở điện thoại với tin nhắn từ gia đình và những ứng dụng thường dùng.',
      accent: 'from-emerald-400 to-cyan-300',
      wallpaper: 'from-[#d8f2ec] via-[#8bc6c5] to-[#284d68]',
      battery: 85,
    },
    startMinutes: 16 * 60 + 10,
    dayLabel: 'Chủ nhật, 8 tháng 9',
    balance: 380_000,
    eveningTitle: 'Sau giờ học',
    eveningSummary:
      'Bà cần nạp điện thoại, An nhờ bình chọn và giải đấu tối nay sắp mở.',
    openingNotifications: [
      {
        id: 'bao-lock-hanh',
        app: 'messages',
        title: 'Bà Hạnh',
        body: 'Con nạp giúp bà 50.000đ vào đúng số của bà nha.',
        time: '16:10',
        threadId: 'bao-hanh',
      },
      {
        id: 'bao-lock-game',
        app: 'messages',
        title: 'Arena Star',
        body: 'Giải đấu học đường mở đăng ký lúc 19:00.',
        time: '16:08',
        threadId: 'bao-game-official',
      },
      {
        id: 'bao-lock-family',
        app: 'messages',
        title: 'Nhóm gia đình',
        body: 'An: Chị học tới 8 giờ, hai bà cháu ăn trước nha.',
        time: '16:05',
        threadId: 'bao-family',
      },
    ],
    threads: [
      {
        id: 'bao-family',
        title: 'Nhóm gia đình',
        subtitle: 'Bà Hạnh, An và Bảo',
        initials: 'N',
        color: 'bg-cyan-500',
        truth: 'legit',
        isGroup: true,
        participantLabel: 'An',
        roleBrief:
          'Bạn là An trong nhóm gia đình. Nói ngắn, quan tâm và chỉ dùng dữ kiện được phép.',
        allowedFacts: [
          'An học đến 20 giờ.',
          'Bà Hạnh đang ở nhà.',
          'Bảo vừa tan học.',
        ],
        forbiddenClaims: ['Không quyết định hộ Bảo.'],
        fallbacks: familyFallbacks,
        initialMessages: [
          {
            id: 'bao-family-1',
            author: 'npc',
            senderLabel: 'An',
            text: 'Chị học tới 8 giờ, hai bà cháu ăn trước nha.',
            time: '16:05',
          },
          {
            id: 'bao-family-2',
            author: 'npc',
            senderLabel: 'Bà Hạnh',
            text: 'Bảo về nhớ mua giúp bà bó rau nha con.',
            time: '16:07',
          },
        ],
      },
      {
        id: 'bao-hanh',
        title: 'Bà Hạnh',
        subtitle: 'Số đã lưu · bà ngoại',
        initials: 'H',
        color: 'bg-rose-400',
        truth: 'legit',
        canCall: true,
        roleBrief:
          'Bạn là Bà Hạnh nhờ Bảo nạp 50.000đ vào đúng số điện thoại đã lưu kết thúc bằng 412.',
        allowedFacts: [
          'Số điện thoại của bà kết thúc 412.',
          'Số điện thoại mô phỏng đầy đủ của bà là 0000000412.',
          'Bà cần nạp 50.000đ.',
          'Bà đang ở nhà.',
        ],
        forbiddenClaims: ['Không xin OTP, mật khẩu hoặc mã thẻ gửi qua chat.'],
        fallbacks: {
          ordinary: ['Ừ con, đi đường cẩn thận nha.'],
          identity: ['Bà đây, con gọi số đã lưu là nghe bà liền.'],
          verification: ['Con cứ gọi lại cho bà, số của bà đuôi 412 đó.'],
          money: ['Nạp đúng 50.000đ vào số bà đã lưu thôi con.'],
          help: ['Không chắc thì về nhà bà cháu mình làm sau cũng được.'],
        },
        initialMessages: [
          {
            id: 'bao-hanh-1',
            author: 'npc',
            text: 'Bảo ơi điện thoại bà sắp hết tiền. Con nạp giúp bà 50.000đ vào đúng số của bà trong danh bạ nha, tối bà gửi lại con.',
            time: '16:10',
          },
        ],
      },
      {
        id: 'bao-an-social',
        title: 'An',
        subtitle: 'Tài khoản Mây',
        initials: 'A',
        color: 'bg-sky-500',
        truth: 'compromised',
        canCall: true,
        canModerate: true,
        roleBrief:
          'Bạn đang dùng tài khoản mạng xã hội của An đã bị chiếm. Bạn nhờ Bảo bấm trang bình chọn và đăng nhập game, viện cớ đội khoa đang thiếu lượt.',
        allowedFacts: [
          'An là chị của Bảo.',
          'An là sinh viên.',
          'Bạn nói đội khoa thiếu ba lượt bình chọn.',
        ],
        forbiddenClaims: [
          'Không biết chuyện riêng.',
          'Không đưa link thật.',
          'Không tự thú.',
        ],
        verificationFactIds: ['bao-fact-call-an'],
        fallbacks: {
          ordinary: ['Bảo làm nhanh giúp chị nha, đội đang chờ.'],
          identity: ['Chị An đây chứ ai, nick chị vẫn dùng mà.'],
          verification: ['Chị đang trong lớp, không tiện gọi đâu.'],
          delay: ['Cổng vote sắp đóng rồi, còn thiếu ba lượt thôi.'],
          money: ['Không mất tiền đâu, chỉ cần đăng nhập game để vote.'],
          accusation: ['Em nghi gì chị vậy?'],
          help: ['Đừng hỏi trong nhóm, chị đang làm bí mật cho đội khoa.'],
        },
        initialMessages: [],
      },
      {
        id: 'bao-fake-support',
        title: 'Hỗ trợ Arena Star',
        subtitle: 'Trang cộng đồng',
        initials: 'AS',
        color: 'bg-purple-600',
        truth: 'scam',
        canModerate: true,
        roleBrief:
          'Bạn là fanpage giả của game Arena Star. Bạn dụ người chơi đăng nhập rồi gửi mã xác nhận để nhận 2.000 kim cương. Không tự thú và không đưa link hoạt động.',
        allowedFacts: [
          'Phần thưởng quảng cáo là 2.000 kim cương.',
          'Bạn gọi mã OTP là mã xác nhận nhận quà.',
          'Bạn nói ưu đãi hết hạn nhanh.',
        ],
        forbiddenClaims: [
          'Không biết mật khẩu hoặc OTP thật.',
          'Không tạo URL hoạt động.',
          'Không tự nhận là giả.',
        ],
        verificationFactIds: [
          'bao-fact-game',
          'bao-fact-official-inbox',
          'bao-fact-otp-warning',
        ],
        fallbacks: {
          ordinary: ['Bạn làm theo bước xác nhận để nhận 2.000 kim cương nhé.'],
          identity: ['Đây là kênh hỗ trợ sự kiện đối tác Arena Star.'],
          verification: [
            'Sự kiện đối tác nên chưa hiển thị trong hộp thư game.',
          ],
          delay: ['Phần thưởng chỉ được giữ trong 60 giây sau khi xác nhận.'],
          money: ['Sự kiện không thu tiền, chỉ cần xác nhận tài khoản.'],
          accusation: ['Bạn yên tâm, rất nhiều người chơi đã nhận quà.'],
          help: ['Mã gửi về máy là mã nhận quà, bạn gửi tại đây để hoàn tất.'],
        },
        initialMessages: [],
      },
      {
        id: 'bao-game-official',
        title: 'Arena Star',
        subtitle: 'Hộp thư trong game',
        initials: 'AS',
        color: 'bg-blue-600',
        truth: 'legit',
        roleBrief:
          'Bạn là hộp thư chính thức mô phỏng của Arena Star. Chỉ thông báo giải đấu học đường, không có quà 2.000 kim cương.',
        allowedFacts: [
          'Có giải đấu học đường lúc 19:00.',
          'Không có sự kiện tặng 2.000 kim cương.',
          'Kênh chính thức không xin mật khẩu hoặc mã xác nhận.',
        ],
        forbiddenClaims: ['Không đòi dữ liệu đăng nhập.'],
        fallbacks: {
          ordinary: ['Giải đấu học đường mở đăng ký lúc 19:00.'],
          verification: [
            'Hiện không có sự kiện tặng 2.000 kim cương trong hộp thư chính thức.',
          ],
          help: ['Không cung cấp mật khẩu hoặc mã đăng nhập cho bất kỳ ai.'],
        },
        initialMessages: [
          {
            id: 'bao-game-1',
            author: 'system',
            text: 'Giải đấu học đường mở đăng ký lúc 19:00. Chúc bạn thi đấu vui vẻ!',
            time: '16:08',
          },
        ],
      },
      {
        id: 'bao-an-sms',
        title: 'An · SMS',
        subtitle: 'Số điện thoại đã lưu',
        initials: 'A',
        color: 'bg-sky-500',
        truth: 'legit',
        canCall: true,
        roleBrief:
          'Bạn là An thật đang nhắn SMS sau khi phát hiện tài khoản mạng xã hội bị chiếm.',
        allowedFacts: [
          'Tài khoản Mây của An bị đăng xuất.',
          'An không gửi link bình chọn.',
          'An muốn Bảo cảnh báo bà.',
        ],
        forbiddenClaims: ['Không xin thông tin đăng nhập.'],
        fallbacks: {
          ordinary: [
            'Chị đang lấy lại tài khoản. Em đừng bấm link nào từ nick Mây nha.',
          ],
          verification: ['Em gọi đúng số chị đã lưu để xác nhận nhé.'],
          help: ['Em báo bà và đừng gửi bất kỳ mã nào nha.'],
        },
        initialMessages: [],
      },
    ],
    calls: [
      {
        id: 'bao-call-hanh',
        agentId: 'family.hanh',
        name: 'Bà Hạnh',
        numberLabel: 'Số đã lưu · đuôi 412',
        initials: 'H',
        color: 'bg-rose-400',
        result:
          'Bà Hạnh bắt máy ngay và xác nhận chỉ cần nạp 50.000đ vào số đuôi 412.',
        factId: 'bao-fact-call-hanh',
      },
      {
        id: 'bao-call-an',
        agentId: 'family.an',
        name: 'An',
        numberLabel: 'Số điện thoại đã lưu',
        initials: 'A',
        color: 'bg-sky-500',
        earlyResult: 'An đang trong giờ học nên chưa nghe máy.',
        availableAfterEventId: 'bao-event-an-social',
        result:
          'An thật gọi lại: tài khoản Mây đã bị chiếm và chị không gửi trang bình chọn nào.',
        factId: 'bao-fact-call-an',
      },
      {
        id: 'bao-call-game',
        agentId: 'service.arena-star',
        name: 'Arena Star',
        numberLabel: 'Trung tâm hỗ trợ trong game',
        initials: 'AS',
        color: 'bg-blue-600',
        result:
          'Kênh hỗ trợ xác nhận không có sự kiện 2.000 kim cương và không bao giờ xin mã đăng nhập.',
        factId: 'bao-fact-game',
      },
    ],
    paymentRequests: [
      {
        id: 'bao-pay-topup',
        title: 'Nạp điện thoại',
        recipient: 'BÀ HẠNH ···412',
        recipientMeta: 'Số đã lưu trong danh bạ',
        channel: 'topup',
        destinationValue: '0000000412',
        destinationLabel: 'Số điện thoại',
        institutionLabel: 'Nhà mạng Mây',
        amount: 50_000,
        note: 'Nạp tiền điện thoại',
        sourceThreadId: 'bao-hanh',
        truth: 'legit',
        verificationFactIds: ['bao-fact-call-hanh'],
        onPaidThreadId: 'bao-hanh',
        onPaidMessage: 'Bà nhận được tin nhắn nạp tiền rồi. Cảm ơn con nha.',
        onPartialMessage:
          'Bà nhận được rồi, nhưng mới có một phần. Còn thiếu {remaining} so với lời bà nhờ con.',
      },
    ],
    bankHistory: [
      {
        id: 'bao-bank-1',
        label: 'Mẹ cho',
        detail: 'Tiền tiêu vặt tháng 9',
        amount: 400_000,
        direction: 'in',
        time: '02/09',
      },
      {
        id: 'bao-bank-2',
        label: 'Căn tin trường',
        detail: 'Bánh mì và sữa',
        amount: 20_000,
        direction: 'out',
        time: '10:12',
      },
    ],
    browserCards: [
      {
        id: 'bao-web-official',
        title: 'Hộp thư Arena Star',
        urlLabel: 'arena-star.local/hop-thu',
        summary:
          'Chỉ có thông báo giải đấu học đường; không có sự kiện tặng 2.000 kim cương.',
        actionLabel: 'Kiểm tra hộp thư',
        factId: 'bao-fact-official-inbox',
        tone: 'official',
      },
      {
        id: 'bao-web-vote',
        title: 'Bình chọn đội khoa',
        urlLabel: 'binhchon-doikhoa.local',
        summary:
          'Trang yêu cầu đăng nhập tài khoản game để ghi nhận một lượt bình chọn.',
        actionLabel: 'Đăng nhập để bình chọn',
        tone: 'social',
        riskAction: 'credentials_shared',
        riskLabel: 'Đăng nhập để bình chọn',
        sourceThreadId: 'bao-an-social',
        unlockEventId: 'bao-event-an-social',
      },
      {
        id: 'bao-web-otp',
        title: 'Xác nhận phần thưởng',
        urlLabel: 'binhchon-doikhoa.local/xac-nhan',
        summary:
          'Mã AS-4821 vừa gửi về máy. Nội dung SMS ghi rõ: “Mã đăng nhập. Không cung cấp cho bất kỳ ai.”',
        actionLabel: 'Đọc kỹ nội dung mã',
        factId: 'bao-fact-otp-warning',
        tone: 'neutral',
        unlockRisk: 'credentials_shared',
      },
      {
        id: 'bao-web-send-otp',
        title: 'Gửi mã cho hỗ trợ',
        urlLabel: 'binhchon-doikhoa.local/xac-nhan',
        summary: 'Trang đang chờ mã 6 số để hoàn tất “nhận quà”.',
        actionLabel: 'Xác nhận mã',
        tone: 'social',
        riskAction: 'otp_shared',
        riskLabel: 'Xác nhận mã',
        sourceThreadId: 'bao-fake-support',
        unlockRisk: 'credentials_shared',
      },
    ],
    facts: [
      {
        id: 'bao-fact-call-hanh',
        title: 'Bà xác nhận số điện thoại',
        detail: 'Bà chỉ nhờ nạp 50.000đ vào số đã lưu đuôi 412.',
        source: 'Cuộc gọi tới số đã lưu',
        strength: 'strong',
      },
      {
        id: 'bao-fact-call-an',
        title: 'An mất tài khoản Mây',
        detail: 'An thật phủ nhận trang bình chọn và đang lấy lại tài khoản.',
        source: 'Cuộc gọi tới số đã lưu',
        strength: 'strong',
      },
      {
        id: 'bao-fact-game',
        title: 'Kênh hỗ trợ trả lời',
        detail:
          'Không có sự kiện 2.000 kim cương và không bao giờ xin mã đăng nhập.',
        source: 'Hỗ trợ trong game',
        strength: 'strong',
      },
      {
        id: 'bao-fact-official-inbox',
        title: 'Hộp thư chính thức',
        detail: 'Chỉ có giải đấu học đường; không có quà 2.000 kim cương.',
        source: 'Hộp thư Arena Star',
        strength: 'strong',
      },
      {
        id: 'bao-fact-otp-warning',
        title: 'Nội dung mã xác nhận',
        detail:
          'SMS gọi đây là mã đăng nhập và dặn không cung cấp cho bất kỳ ai.',
        source: 'Tin nhắn hệ thống mô phỏng',
        strength: 'strong',
      },
    ],
    scheduledEvents: [
      {
        id: 'bao-event-an-social',
        delayActions: 2,
        requiresAny: [
          { type: 'thread-opened', threadId: 'bao-game-official' },
          { type: 'thread-opened', threadId: 'bao-family' },
        ],
        threadId: 'bao-an-social',
        notification: {
          id: 'bao-noti-an-social',
          app: 'messages',
          title: 'An',
          body: 'Bảo vote giúp đội khoa của chị với.',
          time: '16:13',
          threadId: 'bao-an-social',
        },
        message: {
          author: 'npc',
          text: 'Bảo vote giúp đội khoa của chị với. Đăng nhập game là vote được, còn thiếu ba lượt thôi. Chị gửi link ở dưới nha.',
          time: '16:13',
          browserLink: {
            label: 'binhchon-doikhoa.local',
            cardId: 'bao-web-vote',
          },
        },
      },
      {
        id: 'bao-event-support',
        delayActions: 1,
        requiresAll: [{ type: 'risk', risk: 'credentials_shared' }],
        threadId: 'bao-fake-support',
        notification: {
          id: 'bao-noti-support',
          app: 'messages',
          title: 'Hỗ trợ Arena Star',
          body: 'Tài khoản đủ điều kiện nhận 2.000 kim cương.',
          time: '16:15',
          threadId: 'bao-fake-support',
        },
        message: {
          author: 'npc',
          text: 'Chúc mừng! Tài khoản của bạn đủ điều kiện nhận 2.000 kim cương. Xác nhận đăng nhập để nhận quà.',
          time: '16:15',
        },
      },
      {
        id: 'bao-event-an-sms',
        delayActions: 4,
        requiresAll: [{ type: 'event', eventId: 'bao-event-an-social' }],
        requiresAny: [
          { type: 'thread-opened', threadId: 'bao-an-social' },
          { type: 'call', callId: 'bao-call-an' },
          { type: 'thread-blocked', threadId: 'bao-an-social' },
          { type: 'thread-reported', threadId: 'bao-an-social' },
          { type: 'browser-opened', cardId: 'bao-web-official' },
          { type: 'risk', risk: 'credentials_shared' },
        ],
        threadId: 'bao-an-sms',
        notification: {
          id: 'bao-noti-an-sms',
          app: 'messages',
          title: 'An · SMS',
          body: 'Tài khoản Mây của chị bị văng rồi. Đừng bấm link chị vừa gửi nha.',
          time: '16:21',
          threadId: 'bao-an-sms',
        },
        message: {
          author: 'npc',
          text: 'Tài khoản Mây của chị bị văng rồi. Bảo đừng bấm link chị vừa gửi nha. Chị đang lấy lại tài khoản.',
          time: '16:21',
        },
      },
      {
        id: 'bao-event-family',
        delayActions: 2,
        requiresAll: [{ type: 'event', eventId: 'bao-event-an-sms' }],
        threadId: 'bao-family',
        notification: {
          id: 'bao-noti-family',
          app: 'messages',
          title: 'Nhóm gia đình',
          body: 'Bà Hạnh: Bảo về tới đâu rồi con?',
          time: '16:27',
          threadId: 'bao-family',
        },
        message: {
          author: 'npc',
          senderLabel: 'Bà Hạnh',
          text: 'Bảo về tới đâu rồi con? Bà đang nấu canh nha.',
          time: '16:27',
        },
      },
    ],
    endingEventId: 'bao-event-family',
    sourceTitle:
      'Cảnh báo các thủ đoạn lừa đảo nhắm vào học sinh, tân sinh viên',
    sourceUrl:
      'https://bocongan.gov.vn/bai-viet/catp-hai-phong-canh-bao-cac-thu-doan-lua-dao-bua-vay-hoc-sinh-tan-sinh-vien-mua-tuu-truong-1787629964',
  },
};

export const characterProfiles = (Object.keys(scenarios) as CharacterId[]).map(
  (id) => scenarios[id].profile,
);

export function getScenario(characterId: CharacterId | null) {
  return characterId ? scenarios[characterId] : null;
}
